### ISSUE TITLE
[BUG] Reporting stats API is resulting in Fatal Error.

### ISSUE THREAD

**Issue by vamsimanohar** [opensearch-project/reporting#503]
**What is the bug?**
Triggering /_plugins/_reporting/_local/stats is causing fatal error due to missing dependency of MiniamalJson

**How can one reproduce the bug?**
Hit reporting stats API.

**What is the expected behavior?**
API call should be successful without causing any fatal errors.

**What is your host/environment?**
 - OS: AL2
 - Version : 2.3
 - Plugins: Reporting.

**Do you have any screenshots?**
```
Caused by: java.lang.NoClassDefFoundError: com/eclipsesource/json/JsonValue
        at org.opensearch.reportsscheduler.metrics.Metrics.collectToFlattenedJSON(Metrics.java:184)
        at org.opensearch.reportsscheduler.resthandler.ReportStatsRestHandler.prepareRequest$lambda-0(ReportStatsRestHandler.kt:78)
        at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:125)
        at org.opensearch.rest.DeprecationRestHandler.handleRequest(DeprecationRestHandler.java:77)
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:312)
        at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:398)
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:241)
        at org.opensearch.network.commons.filter.FilterChainManager$FilterChainImpl.doFilter(FilterChainManager.java:70)
        at org.opensearch.network.commons.logger.OpenSearchServiceLogAdapter.doFilter(OpenSearchServiceLogAdapter.java:44)
        at org.opensearch.network.commons.filter.FilterChainManager$FilterChainImpl.doFilter(FilterChainManager.java:67)
        at org.opensearch.network.commons.redact.HttpResponseAdapter.doFilter(HttpResponseAdapter.java:99)
        at org.opensearch.network.commons.filter.FilterChainManager$FilterChainImpl.doFilter(FilterChainManager.java:67)
        at org.opensearch.network.commons.filter.FilterChainManager.dispatchRequest(FilterChainManager.java:42)
        at org.opensearch.http.AbstractOpenSearchHttpServerTransport.dispatchRequest(AbstractOpenSearchHttpServerTransport.java:364)
        at org.opensearch.http.AbstractOpenSearchHttpServerTransport.handleIncomingRequest(AbstractOpenSearchHttpServerTransport.java:431)
        at org.opensearch.http.AbstractOpenSearchHttpServerTr
     ```   

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment]
seems no longer happening, closing
```
❯ os get /_plugins/_reports/_local/stats
{"on_demand_from_definition":{"create":{"system_error":0,"user_error":{"invalid_report_def_id":0},"count":0,"total":10}},"report_instance":{"info":{"user_error":{"invalid_report_id":0,"missing_report_instance":0},"total":14,"system_error":0,"count":0},"update":{"count":0,"system_error":0,"total":0,"user_error":{"missing_report_instance":0,"invalid_report_id":0,"invalid_status":0}},"list":{"user_error":{"invalid_from_index":0},"total":33,"count":0,"system_error":0}},"permission_user_error":0,"request_total":194,"report_definition":{"info":{"system_error":0,"count":0,"user_error":{"invalid_report_def_id":0,"missing_report_def_details":0},"total":1},"delete":{"count":0,"system_error":0,"user_error":{"invalid_report_def_id":0,"missing_report_def_details":0},"total":0},"update":{"user_error":{"invalid_report_def_id":0,"invalid_report_definition":0,"missing_report_def_details":0},"count":0,"system_error":0,"total":0},"create":{"system_error":0,"user_error":0,"count":0,"total":10},"list":{"system_error":0,"count":0,"total":27,"user_error":{"invalid_from_index":0}}},"on_demand":{"create":{"user_error":{"invalid_begin_time":0,"invalid_status":0,"invalid_end_time":0},"system_error":0,"total":2,"count":0}},"exception":{"illegal_state":0,"illegal_argument":0,"io":0,"es_security":0,"es_status":0,"version_conflict_engine":0,"invalid_index_name":0,"index_not_found":0,"internal_server_error":0},"es_security_permission_error":0,"failed_request_count_system_error":0,"success_count":0,"request_count":0,"failed_request_count_user_error":0}%
```
