### ISSUE TITLE
[BUG] OS Distribution build failed on reporting for 3.0.0

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/reporting#637]
**What is the bug?**
Our 3.0.0 distribution build is currently failing on opensearch-reports on all distribution types tarball, windows zips, debian, rpm because of a `jar hell` issue found in opensearch-reports. Pipeline link is [here](https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/7044). More context below. 

Windows
```
2023-02-02 18:16:22 INFO     Executing "/tmp/tmpincskegu/opensearch-3.0.0/bin/opensearch-plugin install --batch file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip" in /tmp/tmpincskegu/opensearch-3.0.0
-> Installing file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip
-> Downloading file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip
-> Failed installing file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip
-> Rolling back file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip
-> Rolled back file:/tmp/tmpincskegu/opensearch-reports-scheduler-3.0.0.0.zip
Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-reports-scheduler due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:681)
	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:862)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:830)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:66)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.google.common.annotations.Beta
jar1: /tmp/tmpincskegu/opensearch-3.0.0/plugins/.installing-14976970994818525932/guava-31.0.1-jre.jar
jar2: /tmp/tmpincskegu/opensearch-3.0.0/plugins/opensearch-job-scheduler/guava-31.0.1-jre.jar
	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:667)
	... 11 more
```

Tarball
```
2023-02-02 18:08:52 INFO     Executing "/tmp/tmpc720146a/opensearch-3.0.0/bin/opensearch-plugin install --batch file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip" in /tmp/tmpc720146a/opensearch-3.0.0
-> Installing file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip
-> Downloading file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip
-> Failed installing file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip
-> Rolling back file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip
-> Rolled back file:/tmp/tmpc720146a/opensearch-reports-scheduler-3.0.0.0.zip
Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-reports-scheduler due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:681)
	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:862)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:830)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:66)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.google.common.annotations.Beta
jar1: /tmp/tmpc720146a/opensearch-3.0.0/plugins/.installing-11738705301817114629/guava-31.0.1-jre.jar
jar2: /tmp/tmpc720146a/opensearch-3.0.0/plugins/opensearch-job-scheduler/guava-31.0.1-jre.jar
	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:667)
	... 11 more
```

**What is the expected behavior?**
Build should be passing.

**Comment by rupal-bq** [comment]
@zelinh This issue is fixed in main. Can we try build again?

**Comment by rupal-bq** [comment]
Closing this issue as build is working
